version: '2'
services:
    sakuranekoj2ee-mysql:
        container_name: sakuranekoj2ee-mysql
        image: mysql:5.7.12
        # volumes:
        #     - ~/volumes/jhipster/SaKuraNekoJ2EE/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=sakuranekoj2ee
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl
